### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by ayushee10** [ipfs/js-ipfs-http-client#1180]
\node_modules\ipfs-http-client\src\index.js:79
      for await (const entry of get(path, options)) {
          ^^^^^

SyntaxError: Unexpected reserved word
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:626:28)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)

**Comment by achingbrain** [comment]
You are probably running an old version of node - please upgrade to 12 or later

**Comment by ayushee10** [comment]
thanks a ton; it worked!!
