### ISSUE TITLE
Error: pump requires two streams per minimum

### ISSUE THREAD

**Issue by thpun** [ipfs/js-ipfs-http-client#845]
#### Version
`node` : 8.11.3
`js-ipfs-api`: 22.0.1

#### What I did
```javascript
const peerInfos = await ipfs.dht.findprovs(
  "QmcFyu41HeZ2BndWhTrnJtVmTaHn3GqYg7PZtPspL6kTWV",
  { timeout: 1000 }
)
```

#### Expected behaviour
Return array of PeerInfo as said in API documentation

#### Actual behaviour
```
Error: pump requires two streams per minimum
    at pump (/xxx/node_modules/pump/index.js:64:33)
    at streamToValue (/xxx/node_modules/ipfs-api/src/utils/stream-to-value.js:10:3)
    at send (/xxx/node_modules/ipfs-api/src/utils/send-request.js:217:7)
    at f (/xxx/node_modules/once/once.js:25:25)
    at concat (/xxx/node_modules/ipfs-api/src/utils/stream-to-value.js:12:22)
```

**Comment by mmsaffari** [comment]
Has this been solved? I still get the same behavior on js-ipfs-api@24.0.1
Is there a workaround?

**Comment by alanshaw** [comment]
This should now be resolved - no more `pump` in this module.
