### ISSUE TITLE
Babel error in upload-file-via-browser example

### ISSUE THREAD

**Issue by autonome** [ipfs/js-ipfs-http-client#968]
Follow the readme directions, and I see this:

MacBook:upload-file-via-browser dietrich$ npm start

> upload-file-via-browser@1.0.0 start /Users/dietrich/misc/js-ipfs-http-client/examples/upload-file-via-browser
> node server.js

Listening at localhost:3000
✖ ｢wdm｣: Hash: a12059f5b30f6dcc8c8e
Version: webpack 4.25.1
Time: 566ms
Built at: 04/12/2019 3:30:42 PM
    Asset     Size  Chunks             Chunk Names
bundle.js  379 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[0] multi webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./src/index 52 bytes {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/ansi-regex/index.js] 135 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:3000] (webpack)-dev-server/client?http://localhost:3000 7.78 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {main} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.11 KiB {main} [built]
[./node_modules/webpack/hot/only-dev-server.js] (webpack)/hot/only-dev-server.js 2.55 KiB {main} [built]
[./src/index.js] 1 KiB {main} [not cacheable] [built] [failed] [1 error]
    + 13 hidden modules

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dietrich/misc/js-ipfs-http-client/examples/upload-file-via-browser/node_modules/babel-loader/lib/index.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./src/index main[2]
ℹ ｢wdm｣: Failed to compile.

**Comment by alanshaw** [comment]
Any chance you can send a PR to fix @autonome?

**Comment by alanshaw** [comment]
Resolved by https://github.com/ipfs/js-ipfs-http-client/pull/970
